#!/bin/bash
###########################################################################
# Description:
#     This script will launch the python script of srl-rpki-agent
#     (forwarding any arguments passed to this script).
#
# Copyright (c) 2018-2023 Nokia, generated by srl-agent-builder
###########################################################################


_term (){
    echo "Caugth signal SIGTERM !! "
    kill -TERM "$child" 2>/dev/null
}

function main()
{
    trap _term SIGTERM
    local virtual_env="/opt/demo-agents/rpki-agent/.venv"
    local main_module="/opt/demo-agents/rpki-agent/srl-rpki-agent.py"

    # source the virtual-environment, which is used to ensure the correct python packages are installed,
    # and the correct python version is used
    source "${virtual_env}/bin/activate"

    VENV_LIB="${virtual_env}/lib/python3.6/site-packages"
    # P2="/usr/local/lib64/python3.6/site-packages"
    # NDK="/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/sdk_protos"
    # since 21.6
    NDK="/usr/lib/python3.6/site-packages/sdk_protos"
    export PYTHONPATH="$VENV_LIB:$NDK:$PYTHONPATH"


    export http_proxy=""
    export https_proxy=""
    export no_proxy=""
    python3 ${main_module} &

    child=$!
    wait "$child"
}

main "$@"
